import React,{useMemo,useState} from "react";import{createRoot}from"react-dom/client";import{CheckCircle,Clock,MapPin,MessageCircle,Phone,Truck,ShieldCheck,Menu,X,ArrowRight,Search,Mail}from"lucide-react";import"./style.css";
const DEFAULT_SERVICES=[["Dry Cleaning",80,"item"],["Shirt Ironing",15,"item"],["Pant Ironing",15,"item"],["Shirt Dry Cleaning",80,"item"],["Pant Dry Cleaning",80,"item"],["Saree Dry Cleaning",150,"item"],["Wash & Fold",60,"kg"],["Blanket Cleaning",250,"item"],["Express Service",50,"item"]];
const wa=localStorage.getItem("freshpress_wa")||"919666022064";const phone=localStorage.getItem("freshpress_phone")||"9666022064";
function App(){const[page,setPage]=useState("home"),[menu,setMenu]=useState(false),[cart,setCart]=useState({}),[order,setOrder]=useState(null),[track,setTrack]=useState(null);
const services=JSON.parse(localStorage.getItem("freshpress_services")||"null")||DEFAULT_SERVICES;
const total=useMemo(()=>Object.entries(cart).reduce((s,[i,q])=>s+services[i][1]*q,0),[cart,services]);
const go=p=>{setPage(p);setMenu(false);window.scrollTo(0,0)};
const waMsg=(name="",address="",service="")=>`Hello FreshPress, I would like to book a pickup. My name is ${name}. My address is ${address}. I need ${service}.`;
const openWA=m=>window.open(`https://wa.me/${wa}?text=${encodeURIComponent(m)}`,"_blank");
function Booking(){const[f,setF]=useState({name:"",mobile:"",whatsapp:"",address:"",landmark:"",date:"",time:"",delivery:"Standard",notes:""});const[done,setDone]=useState(false);
function submit(e){e.preventDefault();if(!Object.keys(cart).length)return alert("Please select at least one service.");const id="FP-"+Date.now().toString().slice(-8);const o={id,...f,total,status:"Booking Confirmed",services:Object.entries(cart).map(([i,q])=>({name:services[i][0],qty:q,price:services[i][1]}))};localStorage.setItem("freshpress_order_"+id,JSON.stringify(o));setOrder(o);setDone(true);openWA(waMsg(f.name,f.address,o.services.map(x=>`${x.name} x${x.qty}`).join(", ")));}return <section className="section"><div className="sectionHead"><span>BOOK A PICKUP</span><h2>We'll collect your clothes from your doorstep.</h2></div>{done?<div className="success"><CheckCircle size={48}/><h2>Booking confirmed!</h2><p>Your Order ID is <b>{order.id}</b></p><p>Estimated total: <b>₹{order.total}</b></p><button className="btn" onClick={()=>go("track")}>Track My Order</button></div>:<form onSubmit={submit} className="booking"><div className="formgrid">{["name","mobile","whatsapp","address","landmark","date","time"].map(k=><label key={k}>{k==="mobile"?"Mobile number":k==="whatsapp"?"WhatsApp number":k[0].toUpperCase()+k.slice(1)}<input required={["name","mobile","address","date","time"].includes(k)} type={k==="date"?"date":k==="time"?"time":"text"} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<label>Delivery preference<select value={f.delivery} onChange={e=>setF({...f,delivery:e.target.value})}><option>Standard</option><option>Express</option></select></label><label>Special instructions<textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label></div><h3>Select services</h3><div className="serviceGrid">{services.map((s,i)=><div className="servicePick" key={i}><div><b>{s[0]}</b><small>₹{s[1]}/{s[2]}</small></div><input min="0" type="number" value={cart[i]||0} onChange={e=>setCart({...cart,[i]:Math.max(0,+e.target.value)})}/></div>)}</div><div className="total"><span>Estimated total</span><strong>₹{total}</strong></div><button className="btn full">Confirm Pickup & Continue to Payment</button></form>}</section>}
function Home(){return <><header className="hero"><div className="heroText"><span className="eyebrow">CLEAN • CARE • DELIVER</span><h1>Fresh Clothes.<br/>Perfectly Clean.<br/><em>Professionally Pressed.</em></h1><p>Professional dry cleaning, laundry and ironing with convenient pickup and delivery.</p><div className="actions"><button className="btn" onClick={()=>go("book")}>Book a Pickup <ArrowRight size={18}/></button><button className="btn ghost" onClick={()=>openWA(waMsg())}><MessageCircle size={18}/> Order on WhatsApp</button></div><div className="trust"><span><ShieldCheck/> Quality Cleaning</span><span><Clock/> Fast Service</span><span><Truck/> Pickup & Delivery</span></div></div><div className="heroImg"><img src="https://images.unsplash.com/photo-1545173168-9f1947eebb7f?auto=format&fit=crop&w=1000&q=80" alt="Freshly cleaned laundry"/></div></header><section className="section"><div className="sectionHead"><span>OUR SERVICES</span><h2>Everything your wardrobe needs.</h2></div><div className="serviceGrid cards">{services.map((s,i)=><div className="card" key={i}><small>0{i+1}</small><h3>{s[0]}</h3><p>Carefully handled with professional cleaning and finishing.</p><strong>₹{s[1]} <small>/{s[2]}</small></strong></div>)}</div></section><section className="offer"><div><span>LIMITED-TIME OFFER</span><h2>20% OFF on your first order</h2><p>Use coupon <b>FRESH20</b> at checkout.</p></div><button className="btn" onClick={()=>go("book")}>Claim Offer</button></section><About/><Contact/></>}
function About(){return <section className="section about"><div><span>ABOUT FRESHPRESS</span><h2>Clothes deserve professional care.</h2><p>FreshPress provides careful garment cleaning, professional ironing, quality inspection, and convenient pickup and delivery. Our goal is simple: return your clothes fresh, clean and ready to wear.</p></div><div className="aboutBox"><CheckCircle/><b>Quality inspection on every order</b><p>We check garments before finishing and delivery.</p></div></section>}
function Contact(){return <section className="section contact"><div className="sectionHead"><span>CONTACT</span><h2>We're here when you need us.</h2></div><div className="contactGrid"><a href={`tel:+${phone}`}><Phone/>Call us</a><a href={`https://wa.me/${wa}`}><MessageCircle/>WhatsApp</a><a href="mailto:hello@freshpress.in"><Mail/>Email</a><div><MapPin/>Your Business Address, Telangana, India</div></div><div className="map">Google Maps location can be configured here.</div></section>}
function ServicesPage(){return <section className="section"><div className="sectionHead"><span>SERVICES & PRICING</span><h2>Simple, transparent pricing.</h2></div><div className="table">{services.map((s,i)=><div key={i}><span>{s[0]}</span><b>₹{s[1]}/{s[2]}</b></div>)}</div><p className="note">Prices may vary depending on garment material, size, stains, and special-care requirements.</p></section>}
function Track(){const[f,setF]=useState({id:"",mobile:""});function find(){const o=JSON.parse(localStorage.getItem("freshpress_order_"+f.id)||"null");setTrack(o||false)}return <section className="section"><div className="sectionHead"><span>TRACK MY ORDER</span><h2>Know exactly where your order is.</h2></div><div className="trackBox"><input placeholder="Order ID (e.g. FP-12345678)" value={f.id} onChange={e=>setF({...f,id:e.target.value})}/><input placeholder="Mobile number" value={f.mobile} onChange={e=>setF({...f,mobile:e.target.value})}/><button className="btn" onClick={find}><Search/> Track Order</button>{track&&track.id&&<div className="timeline">{["Booking Confirmed","Pickup Scheduled","Clothes Received","Cleaning","Ironing/Finishing","Out for Delivery","Delivered"].map((x,i)=><div className={i===0?"active":""} key={x}><span>{i+1}</span>{x}</div>)}<p>Estimated delivery: <b>Based on pickup schedule</b></p><p>Payment status: <b>Pending / Gateway confirmation</b></p></div>}{track===false&&<p className="error">Order not found. Check your Order ID.</p>}</div></section>}
function Offers(){return <section className="section"><div className="sectionHead"><span>OFFERS</span><h2>More freshness, more savings.</h2></div><div className="offerGrid">{["20% OFF on your first order","Free pickup & delivery above ₹499","Refer a friend and get ₹100 OFF"].map((x,i)=><div className="card" key={i}><span>OFFER 0{i+1}</span><h3>{x}</h3><p>Promotional offer — editable by the business owner.</p></div>)}</div></section>}
function Admin(){const[servicesState,setSS]=useState(services);function save(){localStorage.setItem("freshpress_services",JSON.stringify(servicesState));alert("Saved. Refresh the page to see updated prices.")}return <section className="section"><div className="sectionHead"><span>ADMIN DASHBOARD</span><h2>FreshPress controls</h2></div><p>This demo dashboard stores settings in this browser. For production, connect Supabase/Firebase and secure admin authentication.</p>{servicesState.map((s,i)=><div className="adminRow" key={i}><input value={s[0]} onChange={e=>{let a=[...servicesState];a[i][0]=e.target.value;setSS(a)}}/><input type="number" value={s[1]} onChange={e=>{let a=[...servicesState];a[i][1]=+e.target.value;setSS(a)}}/></div>)}<button className="btn" onClick={save}>Save prices</button></section>}
function AppPage(){if(page==="book")return <><Booking/></>;if(page==="services"||page==="pricing")return <ServicesPage/>;if(page==="track")return <Track/>;if(page==="offers")return <Offers/>;if(page==="about")return <About/>;if(page==="contact")return <Contact/>;if(page==="admin")return <Admin/>;return <Home/>}
return <><nav><div className="logo" onClick={()=>go("home")}>Fresh<span>Press</span><small>DRY CLEAN & IRON</small></div><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className={"navlinks "+(menu?"show":"")}><button onClick={()=>go("home")}>Home</button><button onClick={()=>go("services")}>Services</button><button onClick={()=>go("pricing")}>Pricing</button><button onClick={()=>go("book")}>Book Pickup</button><button onClick={()=>go("track")}>Track Order</button><button onClick={()=>go("offers")}>Offers</button><button onClick={()=>go("about")}>About</button><button onClick={()=>go("contact")}>Contact</button><button className="navcta" onClick={()=>go("book")}>Book Pickup</button></div></nav><main><AppPage/></main><footer><div className="logo">Fresh<span>Press</span><small>DRY CLEAN & IRON</small></div><p>Fresh clothes. Zero hassle.</p><button onClick={()=>go("admin")}>Owner Admin</button></footer><button className="wa" onClick={()=>openWA(waMsg())}><MessageCircle/></button></>}
createRoot(document.getElementById("root")).render(<App/>);
